development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:4a9a599f4b24a35bf69810441a6895cd@soldierfish.redistogo.com:11065/
  channel_prefix: little_shop_of_funsies_production
